In [10]:
#Importing the Dependencies
import numpy as np#importing numpy for array operations
import pandas as pd#importing pandas for dataframe management
from sklearn.preprocessing import StandardScaler#for standerdizing the data
from sklearn.model_selection import train_test_split#for splitting the data into training and testing data
from sklearn import svm#support vector machine for classification 
from sklearn.metrics import accuracy_score#for calculating the accuracy percentage to determine how accurate the model is

In [11]:
cancer_data=pd.read_csv('/content/data.csv')

In [12]:
cancer_data.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [13]:
cancer_data.drop(columns='id',axis=1,inplace=True)

In [15]:
cancer_data.head()

  diagnosis  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
0         M        17.99  ...                  0.11890          NaN
1         M        20.57  ...                  0.08902          NaN
2         M        19.69  ...                  0.08758          NaN
3         M        11.42  ...                  0.17300          NaN
4         M        20.29  ...                  0.07678          NaN

[5 rows x 32 columns]

In [16]:
cancer_data.shape

(569, 32)

In [17]:
cancer_data.isnull().sum()

diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [23]:
cancer_data.drop(cancer_data.columns[-1],axis=1,inplace=True) 
#The last column is full of missing values and so we are dropping it

In [24]:
cancer_data.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [28]:
X=cancer_data.drop(columns='diagnosis',axis=1)
Y=cancer_data['diagnosis']
print(X)
print(Y)

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]
0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [29]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [33]:
model=svm.SVC(kernel='linear')
model.fit(x_train,y_train)

SVC(kernel='linear')

In [34]:
predict1=model.predict(x_train)
predict2=model.predict(x_test)

In [35]:
score1=accuracy_score(predict1,y_train)
score2=accuracy_score(predict2,y_test)

In [36]:
print("Accuracy of Training Data Prediction ",score1)
print("Accuracy of Testing Data Prediction ",score2)

Accuracy of Training Data Prediction  0.9648351648351648
Accuracy of Testing Data Prediction  0.956140350877193

In [38]:
#Making a predictive system
input_data=(17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)
#This is where we will be taking the input
input_data_as_numpy=np.asarray(input_data)#Transforming the input data into a array for ease of access
input_data_reshaped=input_data_as_numpy.reshape(1,-1)#reshaping the data
prediction=model.predict(input_data_reshaped)
print(prediction)

#Using a simple if and else systen to display the output
if(prediction[0]=='M'):
  print('Patient has Breast Cancer and needs further medical examination')

else:
  print('Patient does not have Breast Cancer')

['M']
Patient has a Parkinsons and needs further medical examination

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"